ml/Fix no ended state fires for multipleDaySelectionDragHandler
airbnb/HorizonCalendar pull request #212
Opened 2023-02-16 06:27 UTC by xingsuo

## Details

This change fixed the issue that multipleDaySelectionDragHandler never get called when the gestureRecognizer is in `ended` state. 

## Related Issue

N/A

## Motivation and Context

We need this state to fire in order to let the user know the dragging gesture has been ended.

## How Has This Been Tested

Tested in the app which has been integrated with HorizonCalendar.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2023-02-16 22:54 UTC, bryankeller requested changes
Thanks for finding this bug and fixing it! I have a few suggestions to simplify the logic. Let me know if they make sense.

2023-02-16 22:54 UTC, bryankeller commented on Sources/Public/CalendarView.swift
>      let newMultipleDaySelectionDay: Day
```suggestion
```

2023-02-16 22:54 UTC, bryankeller commented on Sources/Public/CalendarView.swift
>        newMultipleDaySelectionDay = intersectedDay
```suggestion
```

2023-02-16 22:54 UTC, bryankeller commented on Sources/Public/CalendarView.swift
> +      multipleDaySelectionDragHandler?(newMultipleDaySelectionDay, gestureRecognizer.state)
```suggestion
      lastMultipleDaySelectionDay = intersectedDay
      multipleDaySelectionDragHandler?(intersectedDay, gestureRecognizer.state)
```

2023-02-16 23:36 UTC, xingsuo commented
> Thanks for finding this bug and fixing it! I have a few suggestions to simplify the logic. Let me know if they make sense.

@bryankeller updated!

2023-02-17 00:10 UTC, bryankeller approved these changes

2023-02-17 00:24 UTC, merged